name: Terraform Environment

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        options:
          -apply
          -destroy
        description: Please select apply or destroy

      environment:
        type: string
        options:
          -us-east-1
          -us-east-2
          -us-west-1
          -us-west-2
        description: Please select region

    jobs:
      deploy:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
         - uses: actions/checkout@v7
           name: Checkout repository

         - name: Create tfvars file
           run: echo "${{ vars.TFVARS }}"> terraform.tfvars

         - name: Setup Terraform
           uses: hashicorp/setup-terraform@v4

         - name: Configure AWS Credentials
           uses: aws-actions/configure-aws-credentials@v6.2.4
           with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ inputs.environment }}

         - name: Terraform init
           run: terraform init -backend-config=key="${{ inputs.environment }}/terraform.tfstate"

         - name: Terraform Apply
           run: |
             if [[ ${{inputs.action}} == "apply" ]]
             then
               terraform apply -auto-approve
             else 
                terraform destroy -auto-approve
              fi
              