name: Cronjob

on: 
  schedule: 
    - cron: '*/5 * * * *'

workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v7
           name: Checkout repository

         - name: Run Command
           run: echo "Hello World"
